return function()
	local emitter = cc.ParticleSystemQuad:createWithTotalParticles(50)
    emitter:setDuration(-1)
    emitter:setPositionType(2)
    emitter:setPosVar(cc.p(0, 0))
    emitter:setGravity(cc.p(0,0))
    emitter:setAngleVar(360)
    emitter:setRotationIsDir(true)
    emitter:setEmitterMode(0)
    emitter:setLife(1)
    emitter:setLifeVar(0)
    emitter:setStartSize(100)
    emitter:setEndSize(100)
    emitter:setStartSizeVar(0)
    emitter:setEndSizeVar(0)
    emitter:setSpeed(20)
    emitter:setStartColor(cc.c4f(0.98, 0.70, 0.18, 1))
    emitter:setEndColor(cc.c4f(0))
    emitter:setEmissionRate(emitter:getTotalParticles()/emitter:getLife())
    emitter:setBlendAdditive(true)
    emitter:setBlendFunc(gl.ONE, gl.ONE_MINUS_SRC_COLOR)
    emitter:setTexture(cc.Director:getInstance():getTextureCache():addImage("particles/fire.png"))
    return emitter
end