


local EQUIP_MATERIAL_LOCALIZE = {
    ["ironIngot"] = _("铁锭"),
    ["steelIngot"] = _("钢锭"),
    ["mithrilIngot"] = _("秘银锭"),
    ["blackIronIngot"] = _("黑铁锭"),
    ["arcaniteIngot"] = _("奥金锭"),
    ["wispOfFire"] = _("火炎之魂"),
    ["wispOfCold"] = _("寒冷之魂"),
    ["wispOfWind"] = _("飓风之魂"),
    ["lavaSoul"] = _("熔火之魂"),
    ["iceSoul"] = _("冰霜之魂"),
    ["forestSoul"] = _("森林之魂"),
    ["infernoSoul"] = _("地狱之魂"),
    ["blizzardSoul"] = _("暴雪之魂"),
    ["fairySoul"] = _("精灵之魂"),
    ["moltenShard"] = _("熔火碎片"),
    ["glacierShard"] = _("冰川碎片"),
    ["chargedShard"] = _("充能碎片"),
    ["moltenShiver"] = _("熔火裂片"),
    ["glacierShiver"] = _("冰川碎块"),
    ["chargedShiver"] = _("充能碎块"),
    ["moltenCore"] = _("熔火内核"),
    ["glacierCore"] = _("冰川内核"),
    ["chargedCore"] = _("充能内核"),
    ["moltenMagnet"] = _("熔火磁石"),
    ["glacierMagnet"] = _("冰川磁石"),
    ["chargedMagnet"] = _("充能磁石"),
    ["challengeRune"] = _("挑战符文"),
    ["suppressRune"] = _("压制符文"),
    ["rageRune"] = _("狂怒符文"),
    ["guardRune"] = _("守望符文"),
    ["poisonRune"] = _("剧毒符文"),
    ["giantRune"] = _("巨人符文"),
    ["dolanRune"] = _("多兰符文"),
    ["warsongRune"] = _("战歌符文"),
    ["infernoRune"] = _("地狱符文"),
    ["arcanaRune"] = _("秘境符文"),
    ["eternityRune"] = _("不朽符文")
}
local EQUIP_LOCALIZE = {
    ["fireSuppressChest"] = _("本地化缺失"),
    ["rageSting"] = _("本地化缺失"),
    ["frostChest"] = _("本地化缺失"),
    ["moltenArmguard"] = _("本地化缺失"),
    ["eternitySting"] = _("本地化缺失"),
    ["rageArmguard"] = _("本地化缺失"),
    ["poisonChest"] = _("本地化缺失"),
    ["blizzardArmguard"] = _("本地化缺失"),
    ["infernoCrown"] = _("本地化缺失"),
    ["dolanSting"] = _("本地化缺失"),
    ["frostCrown"] = _("本地化缺失"),
    ["glacierCrown"] = _("本地化缺失"),
    ["windSuppressSting"] = _("本地化缺失"),
    ["warsongChest"] = _("本地化缺失"),
    ["frostOrb"] = _("本地化缺失"),
    ["poisonArmguard"] = _("本地化缺失"),
    ["coldSuppressArmguard"] = _("本地化缺失"),
    ["eternityOrb"] = _("本地化缺失"),
    ["rageChest"] = _("本地化缺失"),
    ["fireSuppressArmguard"] = _("本地化缺失"),
    ["windSuppressChest"] = _("本地化缺失"),
    ["windSuppressOrb"] = _("本地化缺失"),
    ["blizzardSting"] = _("本地化缺失"),
    ["giantSting"] = _("本地化缺失"),
    ["warsongSting"] = _("本地化缺失"),
    ["dolanChest"] = _("本地化缺失"),
    ["giantArmguard"] = _("本地化缺失"),
    ["poisonCrown"] = _("本地化缺失"),
    ["moltenCrown"] = _("本地化缺失"),
    ["dolanArmguard"] = _("本地化缺失"),
    ["dolanCrown"] = _("本地化缺失"),
    ["blizzardCrown"] = _("本地化缺失"),
    ["giantChest"] = _("本地化缺失"),
    ["fireSuppressOrb"] = _("本地化缺失"),
    ["eternityChest"] = _("本地化缺失"),
    ["infernoSting"] = _("本地化缺失"),
    ["giantCrown"] = _("本地化缺失"),
    ["warsongCrown"] = _("本地化缺失"),
    ["blizzardOrb"] = _("本地化缺失"),
    ["coldSuppressOrb"] = _("本地化缺失"),
    ["infernoOrb"] = _("本地化缺失"),
    ["fireSuppressCrown"] = _("本地化缺失"),
    ["dolanOrb"] = _("本地化缺失"),
    ["giantOrb"] = _("本地化缺失"),
    ["chargedCrown"] = _("本地化缺失"),
    ["eternityArmguard"] = _("本地化缺失"),
    ["rageOrb"] = _("本地化缺失"),
    ["frostArmguard"] = _("本地化缺失"),
    ["warsongOrb"] = _("本地化缺失"),
    ["warsongArmguard"] = _("本地化缺失"),
    ["glacierArmguard"] = _("本地化缺失"),
    ["coldSuppressCrown"] = _("本地化缺失"),
    ["windSuppressCrown"] = _("本地化缺失"),
    ["coldSuppressChest"] = _("本地化缺失"),
    ["fireSuppressSting"] = _("本地化缺失"),
    ["poisonOrb"] = _("本地化缺失"),
    ["infernoChest"] = _("本地化缺失"),
    ["coldSuppressSting"] = _("本地化缺失"),
    ["infernoArmguard"] = _("本地化缺失"),
    ["eternityCrown"] = _("本地化缺失"),
    ["chargedArmguard"] = _("本地化缺失"),
    ["frostSting"] = _("本地化缺失"),
    ["rageCrown"] = _("本地化缺失"),
    ["blizzardChest"] = _("本地化缺失"),
    ["windSuppressArmguard"] = _("本地化缺失"),
    ["poisonSting"] = _("本地化缺失"),
}
local DRAGON_LOCALIZE = {
    ["redDragon"] = _("红龙"),
    ["blueDragon"] = _("蓝龙"),
    ["greenDragon"] = _("绿龙"),
}
local BODY_LOCALIZE = {
    ["crown"] = _("头部"),
    ["chest"] = _("胸部"),
    ["sting"] = _("尾部"),
    ["orb"] = _("法球"),
    ["armguardLeft,armguardRight"] = _("护臂"),
    ["armguardRight"] = _("左护臂"),
    ["armguardLeft"] = _("右护臂"),
}


return {
    equip_material = EQUIP_MATERIAL_LOCALIZE,
    equip = EQUIP_LOCALIZE,
    dragon = DRAGON_LOCALIZE,
    body = BODY_LOCALIZE
}









